### ISSUE TITLE
typoの修正

### ISSUE THREAD

**Issue by Kuehar** [mercari/souzoh-recruitment#3]
Coding Test
[Hacker Rank](https://www.hackerrank.com/)を利用し、Web ブラウザ上で基礎的なアルゴリズムのテストに 1 時間程度取り組んでいただきます。ソフトウェアエンジニアとしての基礎力を確かめる目的で実施**してして**おり、応募者の得意領域を問わず一律の内容です。
※出題文は全て英語です。

Hacker Rank の[Problem Solving(Basic)](https://www.hackerrank.com/skills-verification/problem_solving_basic)と[Problem Solving(Intermediate)](https://www.hackerrank.com/skills-verification/problem_solving_intermediate)の問題が出題されますので、Coding Test の前に Hacker Rank のサイトから問題の傾向を確認いただくことをおすすめします。

細かいところで申し訳ありませんが「ソフトウェアエンジニアとしての基礎力を確かめる目的で実施**してして**おり、」となっているのが気になってしまいました。

**Comment by naopr** [comment]
@Kuehar 指摘いただきありがとうございます！また、反応が遅れてしまい申し訳ありません。 #5 にて修正しました。
